export enum APIError {
  UNAUTHORIZED = "UNAUTHORIZED",
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  TOO_EARLY = "TOO_EARLY",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  INVALID_REQUEST = "INVALID_REQUEST",
  UNSUPPORTED_URL_SCHEME = "UNSUPPORTED_URL_SCHEME",
  RESOURCE_EXCEEDS_MAX_FILE_SIZE = "RESOURCE_EXCEEDS_MAX_FILE_SIZE",
  MAX_GRAPH_SIZE_REACHED = "MAX_GRAPH_SIZE_REACHED",
  FILE_NOT_FOUND = "FILE_NOT_FOUND",
  NOTES_APPLICATION_ERROR = "NOTES_APPLICATION_ERROR",
  HTTP_REQUEST_ERROR = "HTTP_REQUEST_ERROR",
  DOCUMENT_TITLE_NOT_AVAILABLE = "DOCUMENT_TITLE_NOT_AVAILABLE",
}