export enum ErrorMessage {
    NOTE_NOT_FOUND = "NOTE_NOT_FOUND",
    INVALID_MIME_TYPE = "INVALID_MIME_TYPE",
    NOTE_WITH_SAME_TITLE_EXISTS = "NOTE_WITH_SAME_TITLE_EXISTS",
    INVALID_NOTE_STRUCTURE = "INVALID_NOTE_STRUCTURE",
    UNAUTHORIZED = "UNAUTHORIZED",
    INVALID_FILE_ENDING = "INVALID_FILE_ENDING",
}