export enum DialogType {
  CHANGE_LANGUAGE = "CHANGE_LANGUAGE",
  EXPORT_DATABASE = "EXPORT_DATABASE",
  SWITCH_GRAPHS = "SWITCH_GRAPHS",
  IMPORT_LINKS = "IMPORT_LINKS",
  SEARCH = "SEARCH",
  NONE = "NONE",
}
