export enum DialogType {
  CHANGE_LANGUAGE = "CHANGE_LANGUAGE",
  EXPORT_DATABASE = "EXPORT_DATABASE",
  SWITCH_GRAPHS = "SWITCH_GRAPHS",
  CREATE_ONE_NOTE_PER_LINE = "CREATE_ONE_NOTE_PER_LINE",
  SEARCH = "SEARCH",
  NONE = "NONE",
}
