name: Release

on: 
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '19'
    - run: npm i
    - name: Build release package
      working-directory: ./tools
      run: ./buildReleasePackage.sh
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "neno-v*.tar.gz"
        artifactErrorsFailBuild: true
        generateReleaseNotes: true
        token: ${{ secrets.GITHUB_TOKEN }}